import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3001/');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('admin@correo.com');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('123');
  await page.locator('input[name="password"]').press('Enter');
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).click();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).dblclick();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).click();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).click();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).click();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).click();
  await page.getByRole('heading', { name: 'Bienvenido al Sistema' }).hover();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('img', { name: 'Avatar' }).click();
  await page.getByText('admin').click();
  await page.getByText('Usuario de Prueba').click();
  await page.getByRole('button', { name: 'Trabajos' }).click();
  await page.getByRole('button', { name: 'Usuarios' }).click();
  await page.getByRole('button', { name: 'Listado' }).click();
  await page.getByRole('img').filter({ hasText: '.st0 { fill: #0e3f67; }' }).click();
  await page.getByText('.st0 { fill: #0e3f67; } ©').click();
  await page.getByText('© 2026 - Programacion III -').click();
  await page.getByRole('button', { name: 'Usuarios' }).click();
  await page.getByRole('button', { name: 'Usuarios' }).press('ArrowUp');
  await page.getByRole('button', { name: 'Gestión' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Gestión' }).press('ArrowUp');
  await page.getByRole('button', { name: 'Listado' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Gestión' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Trabajos' }).press('Enter');
  await page.getByRole('button', { name: 'Trabajos' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Historial' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Salir' }).press('Tab');
  await page.getByRole('button', { name: 'Usuarios' }).press('Tab');
  await page.getByRole('button', { name: 'Trabajos' }).press('Enter');
  await page.getByRole('button', { name: 'Trabajos' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Historial' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Gestión' }).press('Enter');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Salir' }).press('Tab');
  await page.getByRole('button', { name: 'Usuarios' }).press('Tab');
  await page.getByRole('button', { name: 'Trabajos' }).press('Enter');
  await page.getByRole('button', { name: 'Trabajos' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Historial' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Gestión' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Nuevo Trabajo' }).press('Enter');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Salir' }).press('Enter');
});